//! Cross-checks the Rust port against KAT vectors generated by running
//! the original, unmodified C++ (`equihash-khovratovich/Source/C++11/
//! pow.{h,cc}`, built with a portable-BLAKE2b substitute -- see
//! `README.md` "Build environment" for why the original bundle's
//! `blake/blake2b.cpp` doesn't build on arm64 and what replaced it).
//!
//! Validates raw index-set equality (order-identical, since the
//! original's `FindProof` returns a specific fork-tree traversal order
//! and does not sort before returning -- only `Proof::Test`'s internal
//! duplicate check sorts a *copy*). No wire/minimal encoding is
//! validated: the original defines none (see README.md).

use rk::{Equihash, Seed};
use serde::Deserialize;
use std::fs;

#[derive(Deserialize)]
struct Vector {
    n: u32,
    k: u32,
    seed: u32,
    nonce: u32,
    indices: Vec<u32>,
    verified: bool,
}

fn load_vectors() -> Vec<(String, Vector)> {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/vectors");
    let mut out = Vec::new();
    for entry in fs::read_dir(dir).expect("vectors dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("json") {
            let text = fs::read_to_string(&path).expect("read vector");
            let v: Vector = serde_json::from_str(&text).expect("parse vector");
            out.push((path.file_name().unwrap().to_string_lossy().into_owned(), v));
        }
    }
    assert!(!out.is_empty(), "no vector files found in {dir}");
    out
}

#[test]
fn matches_original_cpp_across_all_vectors() {
    let vectors = load_vectors();
    assert!(
        vectors.len() >= 8,
        "expected at least 8 vector files, found {}",
        vectors.len()
    );

    for (name, v) in vectors {
        assert!(v.verified, "vector {name} was not self-verified by the C++ original");

        let mut eq = Equihash::new(v.n, v.k, Seed::from_u32(v.seed));
        let proof = eq.find_proof();

        assert_eq!(
            proof.nonce, v.nonce,
            "{name}: nonce mismatch (Rust port's FindProof search diverged from the original's)"
        );
        assert_eq!(
            proof.inputs, v.indices,
            "{name}: index set mismatch at (n={}, k={}, seed={}, nonce={})",
            v.n, v.k, v.seed, v.nonce
        );
        assert!(
            proof.test(),
            "{name}: Rust port's own solution failed self-verification"
        );
    }
}
